version: "3.9"
services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: vishalgv10/student-backend:latest   # 🔹 pulls from Docker Hub
    container_name: backend
    restart: always
    environment:
      DB_HOST: mysql
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - mysql

  frontend:
    image: vishalgv10/student-frontend:latest  # 🔹 pulls from Docker Hub
    container_name: frontend
    restart: always
    ports:
      - "3000:80"   # only frontend exposed
    depends_on:
      - backend

volumes:
  mysql_data:
